-- Objective: determine how many bike trips started in each census tract.
-- Step 1: assign each bike station to the appropriate census tract using a spatial join
-- Step 2: joining stations with trip data
-- Step 3: grouping and counting trips by census tract 
-- Step 4: save as table for visualization